// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreLocation;
using MapKit;
using SofiaApp.Host.Entities;
using SofiaApp.iOS.Services;

namespace SofiaApp.iOS
{
	class SofiaClientEnvirontment
	{
		SofiaClientEnvirontment ()
		{
			var data = WebServices.Sofia.GetFirePoints (DeviceLocation, UserGuid);
			foreach (var item in data) {
				var coordinate = new CLLocationCoordinate2D (item.lat, item.lon);
					MapAnnotations.Add (new BasicMapAnnotation (coordinate, "fire", "fire"));
			}
		}

		public void Start () {

		}

		public static SofiaClientEnvirontment Current { get; internal set; } = new SofiaClientEnvirontment ();
		public string UserGuid { get; internal set; } = Guid.NewGuid ().ToString ();
		public GeoPoint DeviceLocation { get; internal set; }
		public List<BasicMapAnnotation> MapAnnotations { get; internal set; } = new List<BasicMapAnnotation> ();
	}
}
