// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SofiaApp.iOS
{
	public partial class MapViewController : UIViewController
	{
		public MapViewController (IntPtr handle) : base (handle)
		{
		
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();
		}

		public override void LoadView ()
		{
			base.LoadView ();

			var annotations = SofiaClientEnvirontment.Current.MapAnnotations.ToArray ();
			mapViewContent.Map.AddAnnotations (annotations);

			var mapDelegate = new MapDelegate (this);
			mapViewContent.Map.Delegate = mapDelegate;
		}
	}
}
