// This file has been autogenerated from a class added in the UI designer.

using System.Collections.Generic;
using CoreLocation;

namespace SpaceAppNative.iOS
{
	static class MapService
	{
		public static List<BasicMapAnnotation> Pois = new List<BasicMapAnnotation> ();
		public static BasicMapAnnotation Example1 = new BasicMapAnnotation (new CLLocationCoordinate2D (39.40995469, -0.42555814), "Incendio en ", "Foco 1");
		public static BasicMapAnnotation Example2 = new BasicMapAnnotation (new CLLocationCoordinate2D (39.40995469, -0.42555814), "Incendio", "Foco 2");

		static MapService ()
		{
			Pois.Add (Example1);
			Pois.Add (Example2);
			Pois.Add (new BasicMapAnnotation (new CLLocationCoordinate2D (39.38713867, -0.42658811), "Incendio en pantano de Chera", "Foco 2"));
			Pois.Add (new BasicMapAnnotation (new CLLocationCoordinate2D (39.53433349, -0.4641816), "Incendio en Chera", "Foco 1"));
			Pois.Add (new BasicMapAnnotation (new CLLocationCoordinate2D (39.52829201, -0.51124813), "Incendio en Chelva", "Foco 1"));
		}
	}

}
