// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SpaceAppNative.iOS
{
	public partial class HomeViewController : UIViewController
	{
		public HomeViewController (IntPtr handle) : base (handle)
		{
            //Este es mi test
            //dsadsadass
            //tengo una vac
		}
		partial void fireAlertAction (NSObject sender)
		{
			StaticHelper.ShowDialog (this);
		}
	}
}
