// This file has been autogenerated from a class added in the UI designer.

using System;
using MapKit;
using UIKit;

namespace SofiaApp.iOS
{
	class MapDelegate : MKMapViewDelegate
	{
		protected string annotationIdentifier = "BasicAnnotation";
		//UIButton detailButton;
		MapViewController parent;

		public MapDelegate (MapViewController parent)
		{
			this.parent = parent;
		}

		/// <summary>
		/// This is very much like the GetCell method on the table delegate
		/// </summary>
		public override MKAnnotationView GetViewForAnnotation (MKMapView mapView, IMKAnnotation annotation)
		{
			if (annotation is MKPointAnnotation) {
				return null;
			}

			// try and dequeue the annotation view
			var annotationView = mapView.DequeueReusableAnnotation (annotationIdentifier);

			// if we couldn't dequeue one, create a new one
			if (annotationView == null) {
				annotationView = new MKAnnotationView (annotation, annotationIdentifier);
				annotationView.CanShowCallout = true;
			} else // if we did dequeue one for reuse, assign the annotation to it
				annotationView.Annotation = annotation;

			// configure our annotation view properties
			var image = UIImage.FromFile ("marker-fake.png");
			if (annotationView != null) {
				annotationView.Image = image;
			}
			return annotationView;
		}

		// as an optimization, you should override this method to add or remove annotations as the 
		// map zooms in or out.
		public override void RegionChanged (MKMapView mapView, bool animated) { }
	}

}
